shell:
  program: /bin/bash


font:
  normal:
    family: Menlo
    style: Regular
  
  bold:
    family: Menlo
    style: Bold

  italic:
    family: Menlo
    style: Italic

  bold_italic:
    family: Menlo
    style: Bold Italic

  size: 12



colors:
  primary:
    background: '#1B1D1E'
    foreground: '#F8F8F2'
  #normal:
    #black:   '#333333'
    #red:     '#C4265E'
    #green:   '#86B42B'
    #yellow:  '#B3B42B'
    #blue:    '#6A7EC8'
    #magenta: '#8C6BC8'
    #cyan:    '#56ADBC'
    #white:   '#E3E3DD'
  normal:
    black:   '#666666'
    red:     '#F92672'
    green:   '#A6E22E'
    yellow:  '#E2E22E'
    blue:    '#819AFF'
    magenta: '#AE81FF'
    cyan:    '#66D9EF'
    white:   '#F8F8F2'


# Colors (Molokai Dark)
#colors:
  #primary:
    #background: '#1B1D1E'
    #foreground: '#F8F8F2'
  #normal:
    #black:   '#333333'
    #red:     '#C4265E'
    #green:   '#86B42B'
    #yellow:  '#B3B42B'
    #blue:    '#6A7EC8'
    #magenta: '#8C6BC8'
    #magenta: '#8C6BC8'
    #cyan:    '#56ADBC'
    #white:   '#E3E3DD'
  #bright:
    #black:   '#666666'
    #red:     '#F92672'
    #green:   '#A6E22E'
    #yellow:  '#E2E22E'
    #blue:    '#819AFF'
    #magenta: '#AE81FF'
    #cyan:    '#66D9EF'
    #white:   '#F8F8F2'

